/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dropincoming;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jbf
 */
public class ScreenShotPanel extends javax.swing.JPanel {

    BufferedImage screenShot;
    int oldh= -1;
    int oldw= -1;

    /**
     * Creates new form ScreenShotPanel
     */
    public ScreenShotPanel() {
        initComponents();
        
    }

    @Override
    protected void paintComponent(Graphics g) {
        if ( oldh!=imageLabel.getHeight() || oldw!=imageLabel.getWidth() ) {
            updateImage();
        } 
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
    }

    
    public void takeScreenshot() {
        try {
            Robot robot = new Robot();
            Toolkit t = Toolkit.getDefaultToolkit();
            Dimension d = t.getScreenSize();
            int x = 0;
            int y = 0;
            int width = (int) d.getWidth();
            int height = (int) d.getHeight();
            Rectangle rect = new Rectangle(x, y, width, height);
            screenShot = robot.createScreenCapture(rect);

            // Get the current date and time
            Calendar calendar = Calendar.getInstance();

            // Create a SimpleDateFormat object to format the date and time
            SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss");

            // Generate the file name
            String fileName = "/tmp/dropPanel/" + sdf.format(calendar.getTime()) + ".png";

            filenameLabel.setText(fileName);
            
            updateImage();
            
        } catch (AWTException ex) {
            
            filenameLabel.setText("unable to capture screenshot");
            
        }


    }

    private void updateImage() {
        int w= imageLabel.getWidth();
        int h= imageLabel.getHeight();
        oldw= w;
        oldh= h;
        double aspect= screenShot.getWidth() / (double)screenShot.getHeight();
        if ( w==0 || h==0 ) return;
        if ( h < w/aspect ) {
            w= (int)(h*aspect);
        } else if ( w>h*aspect ) {
            h= (int)(w/aspect);
        }
        Image im= screenShot.getScaledInstance( w, h, Image.SCALE_AREA_AVERAGING );
        imageLabel.setIcon( new ImageIcon( im ));
        
    }
    
    public void writeScreenshot() throws IOException {
        String fileName = filenameLabel.getText();

        // Print the file name
        System.out.println("File name: " + fileName);
        ImageIO.write(screenShot, "png", new File(fileName));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filenameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();

        filenameLabel.setText("jLabel1");

        jButton1.setText("pick...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filenameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filenameLabel)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser= new JFileChooser( new File(filenameLabel.getText()) );
        chooser.setFileFilter( new FileNameExtensionFilter("png files", "png", "PNG") );
        int o= chooser.showSaveDialog(this);
        if ( o==JFileChooser.APPROVE_OPTION ) {
            filenameLabel.setText( chooser.getSelectedFile().toString() );
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
